# Generated by Django 5.2.6 on 2025-09-16 00:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('meaning', models.CharField(max_length=125)),
                ('hand_configuration', models.URLField()),
                ('articulation_point', models.CharField(choices=[('TESTA', 'testa'), ('BOCA', 'boca'), ('TRONCO', 'tronco'), ('NEUTRO', 'neutro'), ('BRAÇO', 'braço')])),
                ('movement', models.CharField()),
                ('body_expression', models.CharField()),
                ('direction_and_orientation', models.CharField()),
            ],
        ),
    ]
