# Generated by Django 5.2.5 on 2025-09-26 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7280da89-8633-4e5d-b2c2-240a95e2af32'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bad07fb5-c6c2-4dec-97da-ea305ef5ffb0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
