# Generated by Django 5.2.5 on 2025-09-23 22:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c9680bf5-dab2-4a5c-bdde-ec8b777058bd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Coloque o nome do sinal que você está criando')),
                ('media', models.FileField(help_text='Coloque o arquivo que deseja subir', upload_to='')),
                ('knowledge_sector', models.CharField(choices=[('Exatas', 'Ciências Exatas'), ('Humanas', 'Ciências Humanas'), ('Linguagens', 'Linguagens e suas tecnologias'), ('Natureza', 'Ciências Naturais e suas Tecnologias'), ('Saúde', 'Ciências da Saúde')], help_text='De que área esse conhecimento é pertencente')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sign')),
            ],
        ),
    ]
