# Generated by Django 5.2.5 on 2025-11-18 23:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('48346102-739a-4e5a-bb8a-a46bc4f4c0ed'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1f72e311-bd26-432a-9ec2-4d1ad7c989b2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
