# Generated by Django 5.2.5 on 2025-09-23 22:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sign_id_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f07d2216-0e74-4941-9a7d-d5a17051f4d3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('273f5dcf-8fe1-44cb-ba0b-f5c398fe54cf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='sign',
            field=models.ForeignKey(help_text='Qual é o sinal do video', on_delete=django.db.models.deletion.CASCADE, to='api.sign'),
        ),
    ]
