# Generated by Django 5.2.5 on 2025-09-26 17:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('488b3bee-fa31-4222-94d8-592786f20421'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d05a22f-670f-4ab4-bca1-85fbe9217295'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
