# Generated by Django 5.2.5 on 2025-08-31 16:14

import django.contrib.auth.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_individual_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Teatcher',
            fields=[
                ('individual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.individual')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.individual',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('path', models.URLField(max_length=255)),
                ('description', models.CharField(blank=True, verbose_name=255)),
                ('knowledge_sector', models.CharField(choices=[('Ling', 'Linguagens'), ('Math', 'Matematica'), ('Humn', 'Humanidades'), ('Natr', 'Natureza'), ('Saud', 'Saude e Qualidade de Vida')], max_length=4)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.individual')),
            ],
        ),
    ]
