# Generated by Django 5.2.5 on 2025-11-20 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('afbe31b9-c38d-437a-b647-316e3e279db7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e38108c1-762f-42d4-a62d-8303ea3787d9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
