# Generated by Django 5.2.5 on 2025-08-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_knowledgesector_teatcher_video'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'permissions': [('can_upload_video', 'User can upload videos in platform'), ('can_delete_own_video', 'User can delete his own video on the platform'), ('can_modify_own_video', 'User can modify own video in platform'), ('can_modify_own_video_name', 'User can modify the name of the own video in platform'), ('can_modify_own_video_description', 'User can modify the description of the own video in platform'), ('can_see_others_video', 'User can watch other users videos in platform')]},
        ),
        migrations.AlterField(
            model_name='individual',
            name='groups',
            field=models.ManyToManyField(related_name='individuals', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='user_permissions',
            field=models.ManyToManyField(related_name='individuals', to='auth.permission'),
        ),
    ]
