# Generated by Django 5.2.5 on 2025-09-26 17:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_email_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6b75134c-53e0-4aee-ad04-2f59f0eac498'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d89c0a66-6281-40e2-b646-db1d9abb4cbb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
