# Generated by Django 5.2.5 on 2025-09-23 22:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sign_id_alter_video_id_alter_video_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ba7f56b1-38bc-4922-a430-6666d05de8a8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('acc9c6f6-6ad1-427f-b748-f05ed03cc4fa'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
