# Generated by Django 5.2.5 on 2025-11-20 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cfce7a54-25c0-4f9e-b423-3f1916c55c1e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('41c5c3b1-903a-4047-b27f-8be6bee7dd8f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
