# Generated by Django 5.2.5 on 2025-09-23 22:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d998bc8a-dee1-420b-a876-fb28b6040c07'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2c21f7ce-fa4a-4e66-b0a8-5c83192af56f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='media',
            field=models.FileField(help_text='Coloque o arquivo que deseja subir', upload_to='uploads/'),
        ),
    ]
