# Generated by Django 5.2.5 on 2025-09-26 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e9835c9c-37ae-4d9e-8566-078dae034610'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('40275575-9f85-41aa-b1fa-fcca8d2f8094'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
