# Generated by Django 5.2.5 on 2025-11-20 22:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e7408a51-a290-49a5-a8ac-fa2d241663d0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('24b426cf-0b76-4aa4-8e76-83ecaff45212'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
