# Generated by Django 5.2.5 on 2025-08-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_individual_options_alter_individual_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={},
        ),
        migrations.AlterModelManagers(
            name='individual',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='teatcher',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='individual',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='individual',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
