# Generated by Django 5.2.5 on 2025-11-20 22:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('521c67d5-92ef-4b20-8aa3-c3db1c5d8f2b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('79cb7639-eec7-428f-82f4-b14e92c86380'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
