# Generated by Django 5.2.5 on 2025-09-26 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20f19f11-5ce0-4154-90fa-73f802c1bd28'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ecad66d0-17cd-4922-bbc5-42f7127de670'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
