# Generated by Django 5.2.5 on 2025-11-20 22:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e02aaf11-9081-4987-bfc0-db490ac7650e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5077d425-3289-4a36-8b24-1c3473925faf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
