# Generated by Django 5.2.5 on 2025-11-20 22:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('860d0f7c-fee9-4a9e-a234-3a899024b814'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('440bb89e-379d-42f0-88bd-b1e2d56e80be'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
