# Generated by Django 5.2.5 on 2025-09-26 17:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3be9fd3b-3deb-4a12-aab5-ab40a0378696'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('77ef2932-a1dc-4fff-9ddd-0edae8b7f809'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
