# Generated by Django 5.2.5 on 2025-09-26 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4daee316-5449-4c1f-887f-d90969922905'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f956fa3f-e147-43a7-950b-9a8720d9a27e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
