# Generated by Django 5.2.5 on 2025-09-26 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('22eafe1f-0092-4464-bc72-077f6fb178c3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2dad6bd9-e2bb-4e4e-9625-dc75ac1bde26'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
