# Generated by Django 5.2.5 on 2025-09-26 23:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1cc624c5-cdda-4799-93de-ed32793f5a67'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4bed6152-db3c-4d31-986b-bcc4acb04592'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
