# Generated by Django 5.2.5 on 2025-09-26 23:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90f11145-0b82-455b-b335-51d4457ef253'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b71560b0-d695-4c43-8e40-a1763256d3bc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
