# Generated by Django 5.2.5 on 2025-09-30 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ede16fb3-1c11-44a9-bf5f-5c76af998135'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca569a3a-c4eb-41a7-bec3-03a8184e7146'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
