# Generated by Django 5.2.5 on 2025-09-30 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bfcc2f8f-4184-490d-9fff-df93f3347ed6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7ec6c953-7d4c-44ec-a7f3-c71adfd26d82'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
