# Generated by Django 5.2.5 on 2025-09-30 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e39754a2-e989-4282-8cf5-84954f5f5a1d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ee3bf8c-dbc6-40aa-8703-86e514811f42'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
