# Generated by Django 5.2.5 on 2025-10-01 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a3285730-b627-4ed8-82cf-0257b0c69815'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f59ef825-55fb-446c-ba21-7e1b8a021809'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
