# Generated by Django 5.2.5 on 2025-10-01 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0431e79c-dde0-4b72-a7f4-b1534ecb3d7f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4df5cf1f-04e0-4449-b80b-b8c4ef479558'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
