# Generated by Django 5.2.5 on 2025-10-01 20:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='media_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8a9f7e5e-5755-40b3-8b27-c3aa49bd2173'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d127dd2d-8c0b-46a6-abd2-99f4b2cc7663'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
