# Generated by Django 5.2.5 on 2025-10-01 22:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_video_media_filename_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cbe06e4e-39cc-49a6-b5ce-d0645fa84837'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c6248e4-70f2-48c7-b0dc-f7c20dc0f671'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='media_filename',
            field=models.CharField(blank=True, help_text='nome do arquivo que vai ficar dentro do banco de dados', max_length=255),
        ),
    ]
