# Generated by Django 5.2.5 on 2025-10-05 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_sign_id_alter_video_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9ac42c1c-7559-49cb-a625-29aece80e907'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('de28c9b2-642c-4fd5-b186-4222ac78cd96'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
