# Generated by Django 5.2.5 on 2025-10-27 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10a416b2-3852-46c3-9433-65cb1dfbb2c3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4e6dcdd-ac42-4911-a4c5-98c4f8f711ac'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
