# Generated by Django 5.2.5 on 2025-11-23 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97ac544b-01d2-407c-8b39-94a7afede183'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c5b3ff14-f40c-46c9-9bf9-3ca4161c1d0b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='SearchHistoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('df47fc89-21cf-41de-9748-80e4cad6112d'), primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
