# Generated by Django 5.2.5 on 2025-10-27 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('75e83b1c-62cc-48c9-b3b0-29e3b033a226'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3bb453d0-2c29-45cb-8f79-1b92aa01583e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
