# Generated by Django 5.2.5 on 2025-10-27 23:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2d46dfdf-f392-4c04-a242-e9f6dc647203'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('36c763a8-bfa9-47a9-9d7e-64e4a8f010b9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
