# Generated by Django 5.2.5 on 2025-10-28 00:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c6e2ecf-3613-432c-a5df-ef8eb5e04a22'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4ca85ea-fa5e-45d0-ae46-21b87151fb74'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
