# Generated by Django 5.2.5 on 2025-10-30 18:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_sign_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc38ed65-ae25-498a-9d5f-04bc81c0bb6a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.UUID('75b5f668-9053-4e99-817a-fe592d8f973f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
